### ISSUE TITLE
Error importing rbnicsx.backends module 

### ISSUE THREAD

**Issue by RokyC** [RBniCS/RBniCSx#3] opened 2022-06-27 09:56 UTC
Here encounters an error importing rbnicsx.backends module：

/home/roky/anaconda3/envs/dolfinx-lab/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/home/roky/anaconda3/envs/dolfinx-lab/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 249, in link
    self.spawn(linker + ld_args)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/home/roky/anaconda3/envs/dolfinx-lab/bin/mpicxx' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 550, in build_extension
    self.compiler.link_shared_object(
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 251, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/home/roky/anaconda3/envs/dolfinx-lab/bin/mpicxx' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/_cpp/compile_code.py", line 125, in compile_code
    module = cppimport.imp(package_name_with_hash)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/cppimport/__init__.py", line 41, in imp
    return imp_from_filepath(filepath, fullname)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/cppimport/__init__.py", line 71, in imp_from_filepath
    template_and_build(filepath, module_data)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/cppimport/importer.py", line 18, in template_and_build
    build_module(module_data)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/cppimport/build_module.py", line 84, in build_module
    setuptools.setup(**setuptools_args)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 178, in run_commands
    raise SystemExit("error: " + str(msg))
SystemExit: error: command '/home/roky/anaconda3/envs/dolfinx-lab/bin/mpicxx' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roky/PyProject/dolfinx/YPplastic/plastic.py", line 12, in <module>
    import rbnicsx.backends
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/backends/__init__.py", line 18, in <module>
    from rbnicsx.backends.proper_orthogonal_decomposition import (
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/backends/proper_orthogonal_decomposition.py", line 16, in <module>
    from rbnicsx._backends.proper_orthogonal_decomposition import (
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/_backends/proper_orthogonal_decomposition.py", line 18, in <module>
    from rbnicsx._cpp import cpp_library
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/_cpp/__init__.py", line 29, in <module>
    cpp_library = compile_package(
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/_cpp/compile_package.py", line 79, in compile_package
    return compile_code(comm, package_name, package_root, package_file, **kwargs)
  File "/home/roky/anaconda3/envs/dolfinx-lab/lib/python3.8/site-packages/rbnicsx/_cpp/compile_code.py", line 127, in compile_code
    raise RuntimeError(f"Compilation failed: {str(e)}.")
RuntimeError: Compilation failed: error: command '/home/roky/anaconda3/envs/dolfinx-lab/bin/mpicxx' failed with exit code 1.

Here is my conda environment configuration
# packages in environment at /home/roky/anaconda3/envs/dolfinx-lab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
adios2                    2.7.1           mpi_mpich_py38hf40de4c_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_10    conda-forge
blosc                     1.21.1               hd32f23e_0    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.4.26            h06a4308_0  
certifi                   2022.6.15        py38h06a4308_0  
cffi                      1.14.6           py38ha65f79e_0    conda-forge
commonmark                0.9.1                    pypi_0    pypi
cppimport                 22.5.11                  pypi_0    pypi
curl                      7.82.0               h7f8727e_0  
double-conversion         3.1.7                h9c3ff4c_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fenics-basix              0.4.2            py38h43d8883_3    conda-forge
fenics-dolfinx            0.4.1            py38hddf330e_4    conda-forge
fenics-ffcx               0.4.2              pyhb871ab6_1    conda-forge
fenics-libbasix           0.4.2                heb3b609_3    conda-forge
fenics-libdolfinx         0.4.1                h8228e07_4    conda-forge
fenics-ufcx               0.4.2                hb871ab6_1    conda-forge
fenics-ufl                2022.1.0           pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3.2                hca11adc_0    conda-forge
fftw                      3.3.10          mpi_mpich_h8b92f0a_2    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gcc_impl_linux-64         10.3.0              hf2f2afa_16    conda-forge
gcc_linux-64              10.3.0              hc39de41_10    conda-forge
gettext                   0.21.0               hf68c758_0  
git                       2.34.1          pl5262hc120c5b_0  
gl2ps                     1.4.2                h0708190_0    conda-forge
glew                      2.1.0                h9c3ff4c_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
gxx_impl_linux-64         10.3.0              hf2f2afa_16    conda-forge
gxx_linux-64              10.3.0              h2593f52_10    conda-forge
h5py                      3.6.0            py38ha0f2276_0  
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          mpi_mpich_h996c276_1014    conda-forge
hypre                     2.24.0          mpi_mpich_hed3a557_1    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
imageio                   2.19.3             pyhcf75d05_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
jsoncpp                   1.9.4                h4bd325d_3    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-devel_linux-64     10.3.0              he6cfe16_16    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnetcdf                 4.8.0           mpi_mpich_hf07302c_2    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsanitizer              10.3.0              h26c7422_16    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  10.3.0              he6cfe16_16    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtheora                 1.1.1             h7f98852_1005    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
loguru                    0.6.0            py38h578d9bd_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mako                      1.2.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
meshio                    5.3.4                    pypi_0    pypi
metis                     5.1.0             h58526e2_1006    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.1.3            py38h97ac3a3_1    conda-forge
mpich                     4.0.2              h846660c_100    conda-forge
multiphenicsx             0.2.dev1                 pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
mumps-include             5.2.1               ha770c72_11    conda-forge
mumps-mpi                 5.2.1               h7ee95aa_11    conda-forge
ncurses                   6.3                  h7f8727e_2  
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.23.0           py38h3a7f9d9_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1o               h7f8727e_0  
parmetis                  4.0.3             h2a9763c_1005    conda-forge
pcre2                     10.37                he7ceb23_1  
perl                      5.26.2               h14c3975_0  
petsc                     3.17.1          real_h259f340_100    conda-forge
petsc4py                  3.17.1          real_hc9bd64a_100    conda-forge
pillow                    8.3.2            py38h8e6f84c_0    conda-forge
pip                       21.2.4           py38h06a4308_0  
proj                      7.2.0                h277dcde_2    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptscotch                  6.0.9                h253636d_1    conda-forge
pugixml                   1.11.4               h9c3ff4c_0    conda-forge
pybind11                  2.9.2                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0                   pypi_0    pypi
python                    3.8.13               h12debd9_0  
python_abi                3.8                      2_cp38    conda-forge
pyvista                   0.34.1             pyhd8ed1ab_0    conda-forge
rbnicsx                   0.0.dev1                 pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
rich                      12.4.4                   pypi_0    pypi
scalapack                 2.2.0                hd931219_1    conda-forge
scooby                    0.5.12             pyhd8ed1ab_0    conda-forge
scotch                    6.0.9                h3858553_1    conda-forge
setuptools                61.2.0           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
slepc                     3.17.1          real_h2be3150_100    conda-forge
slepc4py                  3.17.1          real_h332632f_100    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlite                    3.38.5               hc218d9a_0  
suitesparse               5.10.1               hd8046ac_0    conda-forge
superlu                   5.2.2                h00795ac_0    conda-forge
superlu_dist              7.2.0                h25dcc4a_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tbb-devel                 2020.2               h4bd325d_4    conda-forge
tk                        8.6.12               h1ccaba5_0  
typing_extensions         4.2.0              pyha770c72_1    conda-forge
ufl4rom                   0.0.dev1                 pypi_0    pypi
utfcpp                    3.2.1                ha770c72_0    conda-forge
vtk                       9.0.1           no_osmesa_py38hb32e23c_107    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      1!161.3030           h7f98852_1    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xtensor                   0.24.2               h924138e_0    conda-forge
xtl                       0.7.4                h4bd325d_0    conda-forge
xz                        5.2.5                h7f8727e_1  
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zlib                      1.2.12               h7f8727e_2  
zstd                      1.5.0                ha95c52a_0    conda-forge

**Comment by francesco-ballarin** [comment] 2022-06-27 11:15
I am not a conda user, but I am afraid that the error is explained by the first two lines

```
/home/roky/anaconda3/envs/dolfinx-lab/compiler_compat/ld: cannot find /lib64/libpthread.so.0
/home/roky/anaconda3/envs/dolfinx-lab/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
```

Can you install `pthread` with conda?

**Comment by francesco-ballarin** [comment] 2022-07-13 12:55
Hi @RokyC , please let us know if that fixed your problem. If I do not hear anything back in a couple of days, I'll assume the issue is solved and I'll close it.

**Closed** 2022-07-14 08:50 UTC
